" my vim configuration
"
" DTH :: 2017-08-02
"     :: revised 2025-04-08

" basic settings
inoremap jk <ESC>

let mapleader = ","

filetype plugin indent on
au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=119
au FileType sas set smartindent
au FileType sas set autoindent
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)

syntax on
set encoding=utf-8

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set number " show line numbers
set relativenumber " show relative line numbers
set showcmd
set cursorline
set showmatch
set ruler

set incsearch
set hlsearch

" ensure that we write in unix line ending not dos/windows
set fileformat=unix
"set nobinary

" give me expected backspace behavior.
set backspace=indent,eol,start

" splits things
" make them open on the right and below current window
set splitbelow
set splitright

" turn off search highlighting
nnoremap <leader><space> :nohlsearch<CR>

" folding
set foldenable
set foldlevelstart=10 " open most folds by default
set foldnestmax=10 " 10 nested fold max
" space open/closes folds
nnoremap <space> za
set foldmethod=indent

set background=dark

set laststatus=2
" colorscheme hybrid_material
colorscheme hackthebox
set background=dark

highlight clear
let g:colors_name="hackthebox"
let g:hybrid_custom_term_colors = 1
let g:enable_bold_font = 1
let g:enable_italic_font=1

highlight LineNr ctermfg=59 " Grey37

" airline
let g:airline_powerline_fonts=1
let g:airline_theme='hybridline'
"let g:airline_theme='hybrid'

" ctrl-p
let g:ctrlp_regexp_search = 1
let g:ctrlp_clear_cache_on_exit = 0

" ALE
let g:ale_linters = {'python': ['flake8']}
let g:ale_fixers = {'python': ['remove_trailing_lines', 'trim_whitespace', 'autopep8']}

" tagbar
let g:tagbar_ctags_bin = '/usr/local/bin/ctags'

" jedi
" let g:jedi#force_py_version = 3

if (exists('+colorcolumn'))
    set colorcolumn=120
    highlight ColorColumn ctermbg=0
endif

highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

autocmd BufWritePost *.py call Flake8()

com! FormatJSON %!python -m json.tool

command! VisualBlock normal! <C-v>
